inherit_from: ./.rubocop_base.yml

AllCops:
  TargetRubyVersion: 3.0

Naming/BlockForwarding:
  Enabled: false

Style/NestedFileDirname:
  Enabled: false

Lint/RefinementImportMethods:
  Enabled: false
