ignore:
  - 'vendor/**/*'
  - 'bin/*'
  - 'app/controllers/application_controller.rb'
  - 'app/helpers/application_helper.rb'
  - 'app/models/application_record.rb'
  - 'config/application.rb'
  - 'config/boot.rb'
  - 'config/environment.rb'
  - 'config/environments/development.rb'
  - 'config/environments/production.rb'
  - 'config/environments/test.rb'
  - 'config/initializers/application_controller_renderer.rb'
  - 'config/initializers/assets.rb'
  - 'config/initializers/backtrace_silencers.rb'
  - 'config/initializers/content_security_policy.rb'
  - 'config/initializers/cookies_serializer.rb'
  - 'config/initializers/filter_parameter_logging.rb'
  - 'config/initializers/generators.rb'
  - 'config/initializers/inflections.rb'
  - 'config/initializers/mime_types.rb'
  - 'config/initializers/permissions_policy.rb'
  - 'config/initializers/wrap_parameters.rb'
  - 'config/puma.rb'
  - 'config/routes.rb'
  - 'db/migrate/20210909122939_enable_uuid.rb'
  - 'db/schema.rb'
  - 'db/seed.rb'
  - 'doodles/*'
  - 'spec/rails_helper.rb'
  - 'spec/spec_helper.rb'
